### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by Ebaharloo** [white07S/TradingPatternScanner#1]
I get this error can you help me?

C:\Users\*****>pip install TradingPatternScanner-0.1.2.zip
Defaulting to user installation because normal site-packages is not writeable
Processing c:\users\ebaha\tradingpatternscanner-0.1.2.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "C:\Users\ebaha\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\ebaha\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\ebaha\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools\dist.py", line 475, in __init__
          _Distribution.__init__(
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools\dist.py", line 904, in finalize_options
          ep(self)
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools_scm\integration.py", line 127, in infer_version
          _assign_version(dist, config)
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools_scm\integration.py", line 63, in _assign_version
          _version_missing(config)
        File "C:\Users\ebaha\AppData\Local\Temp\pip-build-env-_z8zdzw4\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 108, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for C:\Users\ebaha\AppData\Local\Temp\pip-req-build-cpe0__4u.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by white07S** [comment]
it should work now perfectly fine.
